import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { SignInButton, SignOutButton, useUser } from '@clerk/nextjs';
import styles from './index.module.css';


import { api } from "~/utils/api";
import { env } from "process";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  const user = useUser();
  console.log(user);
  return (
    <>
      <Head>
        <title>Sign Up - Weekly Finance Tracker</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
      <div className={styles.container}>
        {!user.isSignedIn && 
            <SignInButton redirectUrl={env.HOST_URL} mode="modal">
              <button className={styles.signInBtn}>Sign In</button>
            </SignInButton>
          
        }
        {!!user.isSignedIn &&
          <>
            <span className={styles.greetingText}>Hello, {user.user.firstName ? user.user.firstName : user.user.emailAddresses[0]?.emailAddress}! </span>
            <span className={styles.authInfo}>You are signed in with Google</span>
            <SignOutButton>
                <button className={styles.signInBtn}>Sign Out</button>
            </SignOutButton>
          </>
        }
      </div>
      </main>
    </>
  );
};

export default Home;
